## Création de la base de données

On va créer les différentes relations de la base de données Logilivres

In [1]:
CREATE TABLE Librairie 
(
    NumLib INT PRIMARY KEY NOT NULL,
    NomLib TEXT,
    AdresseLib TEXT,
    TelLib TEXT
)

In [6]:
SELECT * FROM Librairie

NumLib	NomLib	AdresseLib	TelLib
1	Chroniques	19 rue Camille Desmoulins, 94230 Cachan	01 41 98 62 62
2	Fontaine	88 rue de Sèvres, 75007 Paris	01 47 83 29 71
3	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	01 43 25 40 93

In [7]:
INSERT INTO Librairie VALUES (1, "Chroniques", "19 rue Camille Desmoulins, 94230 Cachan", "01 41 98 62 62")

Error: UNIQUE constraint failed: Librairie.NumLib

In [4]:
INSERT INTO Librairie (NumLib, NomLib, AdresseLib, TelLib)
VALUES  (2, "Fontaine", "88 rue de Sèvres, 75007 Paris", "01 47 83 29 71"),
        (3, "Shakespeare and Company", "37 rue de la Bûcherie, 75005 Paris", "01 43 25 40 93")

In [5]:
INSERT INTO Librairie (NomLib, AdresseLib, TelLib)
VALUES  ("Fontaine", "88 rue de Sèvres, 75007 Paris", "01 47 83 29 71"),
        ("Shakespeare and Company", "37 rue de la Bûcherie, 75005 Paris", "01 43 25 40 93")

Error: NOT NULL constraint failed: Librairie.NumLib

In [8]:
CREATE TABLE Livre 
(
    NumLivre INT PRIMARY KEY NOT NULL,
    NomLivre TEXT,
    AutLivre TEXT,
    EditeurLivre TEXT,
    PrixLivre NUMERIC
);

INSERT INTO Livre (NumLivre, NomLivre, AutLivre, EditeurLivre, PrixLivre)
VALUES  (1, "La Voie des Rois", "Sanderson, Brandon", "Livre de Poche", 11.9),
        (2, "Brindlewood Bay", "Cordova, Jason", "Storyline", 35),
        (3, "Processus 7", "Darlay, Christine", "Nathan", 24.9),
        (4, "SIG UE8", "Hudin, Oona", "Dunod", 39.9),
        (5, "Astronomie et Astrophysique", "Acker, Agnès", "Dunod", 45)

In [10]:
SELECT * FROM Livre

NumLivre	NomLivre	AutLivre	EditeurLivre	PrixLivre
1	La Voie des Rois	Sanderson, Brandon	Livre de Poche	11.9
2	Brindlewood Bay	Cordova, Jason	Storyline	35
3	Processus 7	Darlay, Christine	Nathan	24.9
4	SIG UE8	Hudin, Oona	Dunod	39.9
5	Astronomie et Astrophysique	Acker, Agnès	Dunod	45

In [11]:
CREATE TABLE Commande 
(
    NumComm INT PRIMARY KEY NOT NULL,
    DateComm DATE,
    NumLib INT
);

INSERT INTO Commande (NumComm, DateComm, NumLib)
VALUES  (1, "19/01/2026", 1),
        (2, "26/01/2026", 3),
        (3, "31/01/2026", 1),
        (4, "05/02/2026", 3)

In [12]:
SELECT * FROM Commande

NumComm	DateComm	NumLib
1	19/01/2026	1
2	26/01/2026	3
3	31/01/2026	1
4	05/02/2026	3

In [13]:
CREATE TABLE Contient 
(
    NumComm INT NOT NULL,
    NumLivre INT NOT NULL,
    QuantiteLivre INT
);

INSERT INTO Contient (NumComm, NumLivre, QuantiteLivre)
VALUES  (1,1,10),
        (1,3,100),
        (1,5,20),
        (2,2,10),
        (2,4,20),
        (3,5,110),
        (4,1,20),
        (4,2,10)

In [14]:
SELECT * FROM Contient

NumComm	NumLivre	QuantiteLivre
1	1	10
1	3	100
1	5	20
2	2	10
2	4	20
3	5	110
4	1	20
4	2	10