In [1]:
.schema

sql
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE "nobel" (
	"Id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Year"	INTEGER,
	"Category"	TEXT,
	"Prize"	TEXT,
	"Motivation"	TEXT,
	"PrizeShare"	TEXT,
	"LaureateID"	INTEGER,
	"LaureateType"	TEXT,
	"FullName"	TEXT,
	"BirthDate"	TEXT,
	"BirthCity"	TEXT,
	"BirthCountry"	TEXT,
	"Sex"	TEXT,
	"OrganizationName"	TEXT,
	"OrganizationCity"	TEXT,
	"OrganizationCountry"	TEXT,
	"DeathDate"	TEXT,
	"DeathCity"	TEXT,
	"DeathCountry"	TEXT
)

In [2]:
SELECT * FROM nobel LIMIT 1

Id	Year	Category	Prize	Motivation	PrizeShare	LaureateID	LaureateType	FullName	BirthDate	BirthCity	BirthCountry	Sex	OrganizationName	OrganizationCity	OrganizationCountry	DeathDate	DeathCity	DeathCountry
1	1901	Chemistry	The Nobel Prize in Chemistry 1901	"in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions"	1/1	160	Individual	Jacobus Henricus van 't Hoff	1852-08-30	Rotterdam	Netherlands	Male	Berlin University	Berlin	Germany	1911-03-01	Berlin	Germany

a) obtenir les catégories dans lesquelles sont attribuées les prix Nobel

In [3]:
SELECT DISTINCT category FROM nobel

Category
Chemistry
Literature
Medicine
Peace
Physics
Economics

b) lister par ordre alphabétique ( sans doublon) les lauréats du prix Nobel nés en France ou travaillant pour une organisation Française ;

In [4]:
SELECT DISTINCT FullName AS "Nom", Category AS "Catégorie", Year AS "Année" 
FROM nobel
WHERE BirthCountry = "France"
OR OrganizationCountry = "France"
ORDER BY Fullname

Nom	Catégorie	Année
Alain Aspect	Physics	2022
Albert Fert	Physics	2007
Alexis Carrel	Medicine	1912
Alfred Kastler	Physics	1966
Alfred Werner	Chemistry	1913
Anatole France	Literature	1921
André Frédéric Cournand	Medicine	1956
André Lwoff	Medicine	1965
André Paul Guillaume Gide	Literature	1947
Anne L'Huillier	Physics	2023
Annie Ernaux	Literature	2022
Antoine Henri Becquerel	Physics	1903
Aristide Briand	Peace	1926
Charles Edouard Guillaume	Physics	1920
Charles Jules Henri Nicolle	Medicine	1928
Charles Louis Alphonse Laveran	Medicine	1907
Charles Robert Richet	Medicine	1913
Claude Cohen-Tannoudji	Physics	1997
Emmanuelle Charpentier	Chemistry	2020
Esther Duflot	Economics	2019
Ferdinand Buisson	Peace	1927
François Jacob	Medicine	1965
François Mauriac	Literature	1952
Françoise Barré-Sinoussi	Medicine	2008
Frédéric Joliot	Chemistry	1935
Frédéric Mistral	Literature	1904
Frédéric Passy	Peace	1901
Gabriel Lippmann	Physics	1908
Georges Charpak	Physics	1992
Gerard Debreu	Economics	1983
Gérard Mourou	Physics	2018
Henri Bergson	Literature	1927
Henri Moissan	Chemistry	1906
Ilya Ilyich Mechnikov	Medicine	1908
Irène Joliot-Curie	Chemistry	1935
Jacques Monod	Medicine	1965
Jean Baptiste Perrin	Physics	1926
Jean Dausset	Medicine	1980
Jean Tirole	Economics	2014
Jean-Marie Gustave Le Clézio	Literature	2008
Jean-Marie Lehn	Chemistry	1987
Jean-Paul Sartre	Literature	1964
Jean-Pierre Sauvage	Chemistry	2016
Jules A. Hoffmann	Medicine	2011
Louis Eugène Félix Néel	Physics	1970
Louis Renault	Peace	1907
Luc Montagnier	Medicine	2008
Luis F. Leloir	Chemistry	1970
Léon Jouhaux	Peace	1951
Léon Victor Auguste Bourgeois	Peace	1920
Marie Curie, née Sklodowska	Chemistry	1911
Martin Karplus	Chemistry	2013
Maurice Allais	Economics	1988
Moungi Bawendi	Chemistry	2023
Patrick Modiano	Literature	2014
Paul Henri Benjamin Balluet d'Estournelles de Constant, Baron de Constant de Rebecque	Peace	1909
Paul Sabatier	Chemistry	1912
Pierre Agostini	Physics	2023
Pierre Curie	Physics	1903
Pierre-Gilles de Gennes	Physics	1991
Prince Louis-Victor Pierre Raymond de Broglie	Physics	1929
René Cassin	Peace	1968
Roger Guillemin	Medicine	1977
Roger Martin du Gard	Literature	1937
Romain Rolland	Literature	1915
Serge Haroche	Physics	2012
Seán MacBride	Peace	1974
Sully Prudhomme	Literature	1901
Victor Grignard	Chemistry	1912
Yves Chauvin	Chemistry	2005

c) lister les années où le "Comité international de la Croix Rouge" a obtenu le prix Nobel

d) connaître le nombre de femmes ayant obtenu un prix Nobel

e)  lister les femmes françaises ayant obtenu un prix Nobel depuis 2005 ainsi que la catégorie de ce prix Nobel

f) lister par âge décroissant les lauréats individuels du prix Nobel qui sont toujours en vie (leur DeathYear est alors NULL)

g) rechercher les lauréats dont le nom contient "Curie"