In [1]:
.schema

sql
CREATE TABLE sqlite_sequence(name,seq)
CREATE TABLE "nobel" (
	"Id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"Year"	INTEGER,
	"Category"	TEXT,
	"Prize"	TEXT,
	"Motivation"	TEXT,
	"PrizeShare"	TEXT,
	"LaureateID"	INTEGER,
	"LaureateType"	TEXT,
	"FullName"	TEXT,
	"BirthDate"	TEXT,
	"BirthCity"	TEXT,
	"BirthCountry"	TEXT,
	"Sex"	TEXT,
	"OrganizationName"	TEXT,
	"OrganizationCity"	TEXT,
	"OrganizationCountry"	TEXT,
	"DeathDate"	TEXT,
	"DeathCity"	TEXT,
	"DeathCountry"	TEXT
)

In [2]:
SELECT * FROM nobel LIMIT 1

Id	Year	Category	Prize	Motivation	PrizeShare	LaureateID	LaureateType	FullName	BirthDate	BirthCity	BirthCountry	Sex	OrganizationName	OrganizationCity	OrganizationCountry	DeathDate	DeathCity	DeathCountry
1	1901	Chemistry	The Nobel Prize in Chemistry 1901	"in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions"	1/1	160	Individual	Jacobus Henricus van 't Hoff	1852-08-30	Rotterdam	Netherlands	Male	Berlin University	Berlin	Germany	1911-03-01	Berlin	Germany

a) obtenir les catégories dans lesquelles sont attribuées les prix Nobel

In [3]:
SELECT DISTINCT category FROM nobel

Category
Chemistry
Literature
Medicine
Peace
Physics
Economics

b) lister par ordre alphabétique ( sans doublon) les lauréats du prix Nobel nés en France ou travaillant pour une organisation Française ;

In [4]:
SELECT DISTINCT FullName AS "Nom", Category AS "Catégorie", Year AS "Année" 
FROM nobel
WHERE BirthCountry = "France"
OR OrganizationCountry = "France"
ORDER BY Fullname

Nom	Catégorie	Année
Alain Aspect	Physics	2022
Albert Fert	Physics	2007
Alexis Carrel	Medicine	1912
Alfred Kastler	Physics	1966
Alfred Werner	Chemistry	1913
Anatole France	Literature	1921
André Frédéric Cournand	Medicine	1956
André Lwoff	Medicine	1965
André Paul Guillaume Gide	Literature	1947
Anne L'Huillier	Physics	2023
Annie Ernaux	Literature	2022
Antoine Henri Becquerel	Physics	1903
Aristide Briand	Peace	1926
Charles Edouard Guillaume	Physics	1920
Charles Jules Henri Nicolle	Medicine	1928
Charles Louis Alphonse Laveran	Medicine	1907
Charles Robert Richet	Medicine	1913
Claude Cohen-Tannoudji	Physics	1997
Emmanuelle Charpentier	Chemistry	2020
Esther Duflot	Economics	2019
Ferdinand Buisson	Peace	1927
François Jacob	Medicine	1965
François Mauriac	Literature	1952
Françoise Barré-Sinoussi	Medicine	2008
Frédéric Joliot	Chemistry	1935
Frédéric Mistral	Literature	1904
Frédéric Passy	Peace	1901
Gabriel Lippmann	Physics	1908
Georges Charpak	Physics	1992
Gerard Debreu	Economics	1983
Gérard Mourou	Physics	2018
Henri Bergson	Literature	1927
Henri Moissan	Chemistry	1906
Ilya Ilyich Mechnikov	Medicine	1908
Irène Joliot-Curie	Chemistry	1935
Jacques Monod	Medicine	1965
Jean Baptiste Perrin	Physics	1926
Jean Dausset	Medicine	1980
Jean Tirole	Economics	2014
Jean-Marie Gustave Le Clézio	Literature	2008
Jean-Marie Lehn	Chemistry	1987
Jean-Paul Sartre	Literature	1964
Jean-Pierre Sauvage	Chemistry	2016
Jules A. Hoffmann	Medicine	2011
Louis Eugène Félix Néel	Physics	1970
Louis Renault	Peace	1907
Luc Montagnier	Medicine	2008
Luis F. Leloir	Chemistry	1970
Léon Jouhaux	Peace	1951
Léon Victor Auguste Bourgeois	Peace	1920
Marie Curie, née Sklodowska	Chemistry	1911
Martin Karplus	Chemistry	2013
Maurice Allais	Economics	1988
Moungi Bawendi	Chemistry	2023
Patrick Modiano	Literature	2014
Paul Henri Benjamin Balluet d'Estournelles de Constant, Baron de Constant de Rebecque	Peace	1909
Paul Sabatier	Chemistry	1912
Pierre Agostini	Physics	2023
Pierre Curie	Physics	1903
Pierre-Gilles de Gennes	Physics	1991
Prince Louis-Victor Pierre Raymond de Broglie	Physics	1929
René Cassin	Peace	1968
Roger Guillemin	Medicine	1977
Roger Martin du Gard	Literature	1937
Romain Rolland	Literature	1915
Serge Haroche	Physics	2012
Seán MacBride	Peace	1974
Sully Prudhomme	Literature	1901
Victor Grignard	Chemistry	1912
Yves Chauvin	Chemistry	2005

c) lister les années où le "Comité international de la Croix Rouge" a obtenu le prix Nobel

In [6]:
SELECT Year, Fullname FROM nobel
WHERE FullName LIKE "% Croix Rouge %"

Year	FullName
1917	Comité international de la Croix Rouge (International Committee of the Red Cross)
1944	Comité international de la Croix Rouge (International Committee of the Red Cross)
1963	Comité international de la Croix Rouge (International Committee of the Red Cross)

d) connaître le nombre de femmes ayant obtenu un prix Nobel

In [12]:
SELECT Sex, COUNT(DISTINCT Fullname) AS "Nombre" FROM nobel
GROUP BY Sex

Sex	Nombre
	28
Female	65
Male	912

In [13]:
SELECT Sex, COUNT(Fullname) AS "Nombre" FROM nobel
GROUP BY Sex

Sex	Nombre
	31
Female	67
Male	974

e)  lister les femmes françaises ayant obtenu un prix Nobel depuis 2005 ainsi que la catégorie de ce prix Nobel

In [25]:
SELECT Fullname, Category FROM Nobel
WHERE Sex = "Female"
AND BirthCountry = "France"
AND Year >= 2005

FullName	Category	BirthDate
Françoise Barré-Sinoussi	Medicine	1947-07-30
Emmanuelle Charpentier	Chemistry
Annie Ernaux	Literature
Esther Duflot	Economics
Anne L'Huillier	Physics

f) lister par âge décroissant les lauréats individuels du prix Nobel qui sont toujours en vie (leur DeathYear est alors NULL)

In [26]:
SELECT DISTINCT Fullname FROM nobel
WHERE DeathDate IS Null
ORDER BY BirthDate DESC;

FullName
Malala Yousafzai
Tawakkol Karman
Konstantin Novoselov
Leymah Gbowee
Adam G. Riess
Brian P. Schmidt
May-Britt Moser
Stefan W. Hell
Shinya Yamanaka
Edvard I. Moser
Eric A. Cornell
Barack H. Obama
Carol W. Greider
Craig C. Mello
Hiroshi Amano
Eric Betzig
Koichi Tanaka
Andrew Z. Fire
Takaaki Kajita
Rigoberta Menchú Tum
Andre Geim
Bruce A. Beutler
Wolfgang Ketterle
Roderick MacKinnon
Liu Xiaobo
Thomas C. Südhof
Brian K. Kobilka
Mo Yan
Shuji Nakamura
Kailash Satyarthi
Herta Müller
Jean Tirole
William E. Moerner
Paul Krugman
Jack W. Szostak
Lars Peter Hansen
Orhan Pamuk
Alvin E. Roth
Barry J. Marshall
F. Duncan M. Haldane
Juan Manuel Santos
Bernard L. Feringa
Frank Wilczek
Roger B. Myerson
Carl E. Wieman
Eric S. Maskin
Russell A. Hulse
James E. Rothman
Robert B. Laughlin
Jody Williams
⋮
Louise Glück
Abdulrazak Gurnah
Annie Ernaux
Denis Mukwege
Nadia Murad
Abiy Ahmed
Maria Ressa
Dmitri Mouratov
Alès Bialiatski
Richard Thaler
William Nordhaus
Paul Romer
Abhijit Banerjee
Esther Duflot
Michael Kremer
Paul Milgrom
Robert Wilsonr
Joshua Angrist
David Card
Guido Imbens
Ben Bernanke
Douglas Diamond
Philip Dybvig
ICAN International Campaign to Abolish Nuclear Weapons
WFP World Food Programme
Memorial
Center for Civil Liberties
Anne L'Huillier
Pierre Agostini
Ferenc Krausz
Moungi Bawendi
Louis Brus
Alexeï Iekimov
Katalin Kariko
Drew Weissman
Jon Fosse
Narges Mohammadi
Claudia Goldin
John Hopfield
Geoffrey Hinton
Demis Hassabis
David Baker
John Jumper
Victor Ambros
Gary Ruvkun
Han Kang
Nihon Hidankyo
Daron Acemoglu
Simon Johnson
James Robinson

g) rechercher les lauréats dont le nom contient "Curie"

In [27]:
SELECT FullName, Motivation FROM Nobel
WHERE FullName LIKE "%Curie%"

FullName	Motivation
Pierre Curie	"in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel"
Marie Curie, née Sklodowska	"in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel"
Marie Curie, née Sklodowska	"in recognition of her services to the advancement of chemistry by the discovery of the elements radium and polonium, by the isolation of radium and the study of the nature and compounds of this remarkable element"
Irène Joliot-Curie	"in recognition of their synthesis of new radioactive elements"