![schema relationnel](https://mystery.knightlab.com/schema.png)

In [2]:
SELECT * FROM crime_scene_report
WHERE LOWER(city) = "sql city"
AND LOWER(type) = "murder"
AND date = 20180115

date	type	description	city
20180115	murder	Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".	SQL City

The first witness lives at the last house on "Northwestern Dr"

In [5]:
SELECT id, name, address_street_name, MAX(address_number) FROM person
WHERE LOWER(address_street_name) = "northwestern dr"
HAVING MAX(address_number) = address_number

id	name	address_street_name	MAX(address_number)
14887	Morty Schapiro	Northwestern Dr	4919

In [15]:
SELECT * FROM interview
WHERE person_id IN (
        SELECT id FROM person
        WHERE LOWER(address_street_name) = "northwestern dr"
        ORDER BY address_number DESC
        LIMIT 1
)

person_id	transcript
14887	I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

In [16]:
SELECT * FROM interview
WHERE person_id = 14887

person_id	transcript
14887	I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

The second witness, named Annabel, lives somewhere on "Franklin Ave".

In [17]:
SELECT * FROM person
WHERE LOWER(name) LIKE "%annabel%"
AND LOWER(address_street_name) ="franklin ave"

id	name	license_id	address_number	address_street_name	ssn
16371	Annabel Miller	490173	103	Franklin Ave	318771143

In [18]:
SELECT * FROM interview
WHERE person_id IN (
        SELECT id FROM person
        WHERE LOWER(name) LIKE "%annabel%"
        AND LOWER(address_street_name) ="franklin ave")

person_id	transcript
16371	I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

On sait que :
- Le meurtrier va à Get Fit Now
- Son numéro de membre commence par 48Z
- Il est membre gold
- La plaque de sa voiture comporte les caractères "H42W"
- Il était présent au club le 9 janvier 2018

In [19]:
SELECT DISTINCT membership_status FROM get_fit_now_member

membership_status
gold
regular
silver

In [21]:
SELECT id, person_id, name 
FROM get_fit_now_member gfm, get_fit_now_check_in gfc
WHERE gfm.id = gfc.membership_id
AND id LIKE "48Z%"
AND membership_status = "gold"
AND check_in_date = 20180109

id	person_id	name
48Z7A	28819	Joe Germuska
48Z55	67318	Jeremy Bowers

In [22]:
SELECT p.id, p.name, plate_number
FROM get_fit_now_member gfm, person p, drivers_license d
WHERE gfm.person_id = p.id
AND p.license_id = d.id
AND gfm.id LIKE "48Z%"
AND membership_status = "gold"
AND plate_number LIKE "%H42W%"

id	name	plate_number
67318	Jeremy Bowers	0H42W2

In [23]:
INSERT INTO solution VALUES (1, 'Jeremy Bowers');

SELECT value FROM solution;

value
Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

In [24]:
SELECT * FROM interview
WHERE person_id = 67318

person_id	transcript
67318	I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.

In [25]:
SELECT * FROM drivers_license LIMIT 5

id	age	height	eye_color	hair_color	gender	plate_number	car_make	car_model
100280	72	57	brown	red	male	P24L4U	Acura	MDX
100460	63	72	brown	brown	female	XF02T6	Cadillac	SRX
101029	62	74	green	green	female	VKY5KR	Scion	xB
101198	43	54	amber	brown	female	Y5NZ08	Nissan	Rogue
101255	18	79	blue	grey	female	5162Z1	Lexus	GS

In [26]:
SELECT DISTINCT car_model FROM drivers_license
WHERE car_make = "Tesla"

car_model
Roadster
Model S
Model 3
Model X

In [32]:
SELECT p.id, name, annual_income, COUNT(*) AS "présence concert"
FROM person p, drivers_license d, income i, facebook_event_checkin f
WHERE p.license_id = d.id
AND p.ssn = i.ssn
AND p.id = f.person_id
AND height BETWEEN 65 AND 67
AND hair_color = "red"
AND gender = "female"
AND car_make = "Tesla"
AND car_model = "Model S"
AND event_name = "SQL Symphony Concert"
AND f.date BETWEEN 20171201 AND 20171231
GROUP BY p.id
ORDER BY annual_income DESC

id	name	annual_income	présence concert
99716	Miranda Priestly	310000	3

In [33]:
INSERT INTO solution VALUES (1, 'Miranda Priestly');

SELECT value FROM solution;

value
Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!